apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: yyc-mech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yyc-mech
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
