import type { ModuleData } from "@/types/module";

// 模拟数据 - 优化后的模块数据，确保所有功能名称字数一致（四个字）
export const mockModules: ModuleData[] = [
  {
    id: "01",
    title: "数字人像",
    titleEn: "Digital Avatar",
    description: "一键克隆形象与声音，轻松生成多场景视频",
    descriptionEn:
      "Clone your image and voice with one click, easily generate videos for multiple scenarios",
    features: [
      "形象克隆",
      "音色复制",
      "音频合成",
      "视频生成",
      "文案创作",
      "批量制作",
      "静态数人",
      "直播数人",
    ],
    featuresEn: [
      "Image Clone",
      "Voice Copy",
      "Audio Synthesis",
      "Video Generation",
      "Content Creation",
      "Batch Production",
      "Static Avatar",
      "Live Avatar",
    ],
    icon: "👤",
    isFavorite: false,
    rating: 4.5,
    userRating: 0,
  },
  {
    id: "02",
    title: "智能对话",
    titleEn: "Smart Chat",
    description: "思路对接，就像跟真实文件对话",
    descriptionEn: "Connect ideas, chat with files as if they were real people",
    features: [
      "深度推理",
      "知识对话",
      "对话分享",
      "文件解析",
      "联网搜索",
      "场景对话",
      "对话导出",
      "语义理解",
    ],
    featuresEn: [
      "Deep Reasoning",
      "Knowledge Chat",
      "Chat Sharing",
      "File Analysis",
      "Web Search",
      "Scenario Chat",
      "Chat Export",
      "Semantic Understanding",
    ],
    icon: "💬",
    isFavorite: true,
    rating: 4.8,
    userRating: 5,
  },
  {
    id: "03",
    title: "微信助手",
    titleEn: "WeChat Helper",
    description: "一站式提高微信号管理，AI自动聊天与SOP模拟化客服",
    descriptionEn:
      "One-stop WeChat account management, AI auto-chat and SOP simulated customer service",
    features: [
      "账号管理",
      "智能聊天",
      "关键回复",
      "用户画像",
      "欢迎设置",
      "知识对话",
      "客户跟进",
      "朋友营销",
    ],
    featuresEn: [
      "Account Management",
      "Smart Chat",
      "Key Replies",
      "User Profiling",
      "Welcome Setup",
      "Knowledge Chat",
      "Customer Follow-up",
      "Friend Marketing",
    ],
    icon: "📱",
    isFavorite: false,
    rating: 4.2,
    userRating: 0,
  },
  {
    id: "04",
    title: "智能招聘",
    titleEn: "Smart Recruitment",
    description: "RPA面试平台智能招聘与AI面试，省去大量时间",
    descriptionEn: "RPA interview platform for smart recruitment and AI interviews, saving a lot of time",
    features: [
      "自动筛选",
      "AI面试",
      "流程自动化",
      "人才画像",
      "报告生成",
      "面试安排",
      "简历分析",
      "远程面试",
    ],
    featuresEn: [
      "Auto Screening",
      "AI Interview",
      "Process Automation",
      "Talent Profiling",
      "Report Generation",
      "Interview Scheduling",
      "Resume Analysis",
      "Remote Interview",
    ],
    icon: "🎯",
    isFavorite: false,
    rating: 4.6,
    userRating: 0,
  },
  {
    id: "05",
    title: "模拟陪练",
    titleEn: "Simulation Training",
    description: "多场景模拟对话，实时反馈与提高分析",
    descriptionEn: "Multi-scenario simulation conversations with real-time feedback and improvement analysis",
    features: [
      "场景模拟",
      "实时反馈",
      "角色扮演",
      "技能评估",
      "学习路径",
      "进度跟踪",
      "模拟测试",
      "智能分析",
    ],
    featuresEn: [
      "Scenario Simulation",
      "Real-time Feedback",
      "Role Playing",
      "Skill Assessment",
      "Learning Path",
      "Progress Tracking",
      "Mock Tests",
      "Intelligent Analysis",
    ],
    icon: "🎓",
    isFavorite: true,
    rating: 4.7,
    userRating: 5,
  },
  {
    id: "06",
    title: "流程自动化",
    titleEn: "Process Automation",
    description: "自动化工作流，多模态生成，跨平台部署",
    descriptionEn: "Automated workflows, multimodal generation, cross-platform deployment",
    features: [
      "工作流设计",
      "多模态生成",
      "跨平台部署",
      "任务调度",
      "数据整合",
      "状态监控",
      "异常处理",
      "性能优化",
    ],
    featuresEn: [
      "Workflow Design",
      "Multimodal Generation",
      "Cross-platform Deployment",
      "Task Scheduling",
      "Data Integration",
      "Status Monitoring",
      "Exception Handling",
      "Performance Optimization",
    ],
    icon: "⚙️",
    isFavorite: false,
    rating: 4.4,
    userRating: 0,
  },
  {
    id: "07",
    title: "知识构建",
    titleEn: "Knowledge Building",
    description: "多渠道数据训练，一键应用到行业场景",
    descriptionEn: "Multi-channel data training, one-click application to industry scenarios",
    features: [
      "数据训练",
      "知识图谱",
      "场景应用",
      "智能问答",
      "内容生成",
      "知识更新",
      "权限管理",
      "数据清洗",
    ],
    featuresEn: [
      "Data Training",
      "Knowledge Graph",
      "Scenario Application",
      "Intelligent Q&A",
      "Content Generation",
      "Knowledge Update",
      "Permission Management",
      "Data Cleaning",
    ],
    icon: "📚",
    isFavorite: true,
    rating: 4.5,
    userRating: 4,
  },
  {
    id: "08",
    title: "会议助手",
    titleEn: "Meeting Assistant",
    description: "实时在线记录，多语言翻译，智能摘要",
    descriptionEn: "Real-time online recording, multilingual translation, intelligent summarization",
    features: [
      "实时记录",
      "语音识别",
      "多语言翻译",
      "智能摘要",
      "会议纪要",
      "任务追踪",
      "关键词提取",
      "情感分析",
    ],
    featuresEn: [
      "Real-time Recording",
      "Speech Recognition",
      "Multilingual Translation",
      "Intelligent Summarization",
      "Meeting Minutes",
      "Task Tracking",
      "Keyword Extraction",
      "Sentiment Analysis",
    ],
    icon: "🎙️",
    isFavorite: false,
    rating: 4.3,
    userRating: 0,
  },
  {
    id: "09",
    title: "图片生成",
    titleEn: "Image Generation",
    description: "文字转图，图生图，海报设计与模特换衣",
    descriptionEn: "Text to image, image to image, poster design and model clothing change",
    features: [
      "文字转图",
      "图生图",
      "海报设计",
      "模特换衣",
      "风格迁移",
      "背景替换",
      "图像修复",
      "智能裁剪",
    ],
    featuresEn: [
      "Text to Image",
      "Image to Image",
      "Poster Design",
      "Model Clothing Change",
      "Style Transfer",
      "Background Replacement",
      "Image Restoration",
      "Intelligent Cropping",
    ],
    icon: "🎨",
    isFavorite: true,
    rating: 4.9,
    userRating: 5,
  },
  {
    id: "10",
    title: "思维导图",
    titleEn: "Mind Mapping",
    description: "自动化思维脑图生成，多格式导出",
    descriptionEn: "Automated mind map generation, multi-format export",
    features: [
      "自动生成",
      "头脑风暴",
      "多格式导出",
      "节点编辑",
      "层级管理",
      "协作编辑",
      "主题定制",
      "智能布局",
    ],
    featuresEn: [
      "Auto Generation",
      "Brainstorming",
      "Multi-format Export",
      "Node Editing",
      "Hierarchy Management",
      "Collaborative Editing",
      "Theme Customization",
      "Intelligent Layout",
    ],
    icon: "🧠",
    isFavorite: false,
    rating: 4.4,
    userRating: 0,
  },
  {
    id: "11",
    title: "手机自动化",
    titleEn: "Mobile Automation",
    description: "基于安卓手机的机器人流程自动化，完全无人工",
    descriptionEn: "Robot process automation based on Android phones, completely unattended",
    features: [
      "RPA控制",
      "自动化流程",
      "任务调度",
      "远程控制",
      "数据采集",
      "批量操作",
      "异常处理",
      "定时执行",
    ],
    featuresEn: [
      "RPA Control",
      "Automated Processes",
      "Task Scheduling",
      "Remote Control",
      "Data Collection",
      "Batch Operations",
      "Exception Handling",
      "Scheduled Execution",
    ],
    icon: "🤖",
    isFavorite: true,
    rating: 4.6,
    userRating: 5,
  },
  {
    id: "12",
    title: "项目架构",
    titleEn: "Project Architecture",
    description: "基于ThinkPHP + Vue架构，全端适配",
    descriptionEn: "Based on ThinkPHP + Vue architecture, full-end adaptation",
    features: [
      "架构设计",
      "全端适配",
      "模块化开发",
      "性能优化",
      "安全防护",
      "扩展插件",
      "API设计",
      "部署方案",
    ],
    featuresEn: [
      "Architecture Design",
      "Full-end Adaptation",
      "Modular Development",
      "Performance Optimization",
      "Security Protection",
      "Extension Plugins",
      "API Design",
      "Deployment Solutions",
    ],
    icon: "🏗️",
    isFavorite: false,
    rating: 4.3,
    userRating: 0,
  },
  {
    id: "13",
    title: "营销文案",
    titleEn: "Marketing Copy",
    description: "智能生成多场景营销文案，一键优化提升转化率",
    descriptionEn: "Intelligently generate multi-scenario marketing copy, one-click optimization to improve conversion rate",
    features: [
      "场景文案",
      "一键优化",
      "多维度创作",
      "SEO优化",
      "A/B测试",
      "竞品分析",
      "风格定制",
      "批量生成",
    ],
    featuresEn: [
      "Scenario Copywriting",
      "One-click Optimization",
      "Multi-dimensional Creation",
      "SEO Optimization",
      "A/B Testing",
      "Competitor Analysis",
      "Style Customization",
      "Batch Generation",
    ],
    icon: "📝",
    isFavorite: true,
    rating: 4.7,
    userRating: 4,
  },
  {
    id: "14",
    title: "语音合成",
    titleEn: "Speech Synthesis",
    description: "多语种语音合成与识别，支持情感语调与场景定制",
    descriptionEn: "Multilingual speech synthesis and recognition, supporting emotional intonation and scene customization",
    features: [
      "语音合成",
      "语音识别",
      "多语种支持",
      "情感语调",
      "场景定制",
      "实时转换",
      "音频处理",
      "字幕生成",
    ],
    featuresEn: [
      "Speech Synthesis",
      "Speech Recognition",
      "Multilingual Support",
      "Emotional Intonation",
      "Scene Customization",
      "Real-time Conversion",
      "Audio Processing",
      "Subtitle Generation",
    ],
    icon: "🔊",
    isFavorite: false,
    rating: 4.5,
    userRating: 0,
  },
  {
    id: "15",
    title: "数据分析",
    titleEn: "Data Analysis",
    description: "智能数据分析与可视化，发掘业务洞察与增长点",
    descriptionEn: "Intelligent data analysis and visualization to discover business insights and growth points",
    features: [
      "数据清洗",
      "深度分析",
      "可视化呈现",
      "预测分析",
      "异常检测",
      "关联分析",
      "报表生成",
      "动态监控",
    ],
    featuresEn: [
      "Data Cleaning",
      "Deep Analysis",
      "Visualization Presentation",
      "Predictive Analysis",
      "Anomaly Detection",
      "Correlation Analysis",
      "Report Generation",
      "Dynamic Monitoring",
    ],
    icon: "📊",
    isFavorite: true,
    rating: 4.8,
    userRating: 5,
  },
  {
    id: "16",
    title: "语言翻译",
    titleEn: "Language Translation",
    description: "专业多语言翻译与本地化，支持行业术语定制",
    descriptionEn: "Professional multilingual translation and localization, supporting industry terminology customization",
    features: [
      "多语言翻译",
      "术语库",
      "语境理解",
      "格式保留",
      "行业定制",
      "机器记忆",
      "质量评估",
      "批量处理",
    ],
    featuresEn: [
      "Multilingual Translation",
      "Terminology Database",
      "Context Understanding",
      "Format Preservation",
      "Industry Customization",
      "Machine Memory",
      "Quality Assessment",
      "Batch Processing",
    ],
    icon: "🌐",
    isFavorite: false,
    rating: 4.6,
    userRating: 0,
  },
  {
    id: "17",
    title: "智能学习",
    titleEn: "Intelligent Learning",
    description: "个性化学习计划与技能培训，实时反馈与进度跟踪",
    descriptionEn: "Personalized learning plans and skill training, real-time feedback and progress tracking",
    features: [
      "学习计划",
      "实时反馈",
      "进度跟踪",
      "技能认证",
      "课程推荐",
      "知识图谱",
      "模拟考试",
      "学习分析",
    ],
    featuresEn: [
      "Learning Plans",
      "Real-time Feedback",
      "Progress Tracking",
      "Skill Certification",
      "Course Recommendation",
      "Knowledge Graph",
      "Mock Exams",
      "Learning Analysis",
    ],
    icon: "🎯",
    isFavorite: true,
    rating: 4.7,
    userRating: 5,
  },
  {
    id: "18",
    title: "智能客服",
    titleEn: "Intelligent Customer Service",
    description: "全渠道智能客服系统，7×24小时无缝服务体验",
    descriptionEn: "Omni-channel intelligent customer service system, 7×24 hours seamless service experience",
    features: [
      "全渠道接入",
      "24小时服务",
      "情绪识别",
      "工单管理",
      "智能路由",
      "知识检索",
      "客服质检",
      "报表分析",
    ],
    featuresEn: [
      "Omni-channel Access",
      "24/7 Service",
      "Emotion Recognition",
      "Ticket Management",
      "Intelligent Routing",
      "Knowledge Retrieval",
      "Service Quality Inspection",
      "Report Analysis",
    ],
    icon: "👥",
    isFavorite: false,
    rating: 4.4,
    userRating: 0,
  },
  {
    id: "19",
    title: "法律助手",
    titleEn: "Legal Assistant",
    description: "智能法律咨询与合同审核，降低法务风险与成本",
    descriptionEn: "Intelligent legal consultation and contract review to reduce legal risks and costs",
    features: [
      "法律咨询",
      "合同审核",
      "风险评估",
      "条款生成",
      "案例检索",
      "法律文书",
      "合规检查",
      "费用计算",
    ],
    featuresEn: [
      "Legal Consultation",
      "Contract Review",
      "Risk Assessment",
      "Clause Generation",
      "Case Retrieval",
      "Legal Documents",
      "Compliance Check",
      "Cost Calculation",
    ],
    icon: "⚖️",
    isFavorite: true,
    rating: 4.5,
    userRating: 4,
  },
  {
    id: "20",
    title: "财务管理",
    titleEn: "Financial Management",
    description: "智能财务管理与税务规划，提升财务效率与准确性",
    descriptionEn: "Intelligent financial management and tax planning to improve financial efficiency and accuracy",
    features: [
      "账务处理",
      "税务规划",
      "报表生成",
      "合规检查",
      "预算管理",
      "成本分析",
      "财务预测",
      "风险预警",
    ],
    featuresEn: [
      "Accounting Processing",
      "Tax Planning",
      "Report Generation",
      "Compliance Check",
      "Budget Management",
      "Cost Analysis",
      "Financial Forecasting",
      "Risk Warning",
    ],
    icon: "💹",
    isFavorite: false,
    rating: 4.3,
    userRating: 0,
  },
  {
    id: "21",
    title: "UI/UX设计",
    titleEn: "UI/UX Design",
    description: "智能UI/UX设计与品牌视觉，一键生成多端设计方案",
    descriptionEn: "Intelligent UI/UX design and brand vision, one-click generation of multi-terminal design solutions",
    features: [
      "设计生成",
      "多端适配",
      "品牌一致性",
      "设计系统",
      "原型制作",
      "交互设计",
      "视觉优化",
      "资源导出",
    ],
    featuresEn: [
      "Design Generation",
      "Multi-terminal Adaptation",
      "Brand Consistency",
      "Design System",
      "Prototype Making",
      "Interaction Design",
      "Visual Optimization",
      "Resource Export",
    ],
    icon: "🎨",
    isFavorite: true,
    rating: 4.8,
    userRating: 5,
  },
  {
    id: "22",
    title: "整合营销",
    titleEn: "Integrated Marketing",
    description: "全渠道营销策略与内容生成，提升品牌影响力",
    descriptionEn: "Omni-channel marketing strategies and content generation to enhance brand influence",
    features: [
      "营销策略",
      "内容生成",
      "效果评估",
      "用户分群",
      "渠道整合",
      "活动策划",
      "数据追踪",
      "ROI分析",
    ],
    featuresEn: [
      "Marketing Strategy",
      "Content Generation",
      "Effectiveness Evaluation",
      "User Segmentation",
      "Channel Integration",
      "Activity Planning",
      "Data Tracking",
      "ROI Analysis",
    ],
    icon: "🚀",
    isFavorite: false,
    rating: 4.5,
    userRating: 0,
  },
  {
    id: "23",
    title: "代码生成",
    titleEn: "Code Generation",
    description: "智能代码生成与优化，加速产品研发与迭代",
    descriptionEn: "Intelligent code generation and optimization to accelerate product development and iteration",
    features: [
      "代码生成",
      "性能优化",
      "自动化测试",
      "架构建议",
      "代码审查",
      "文档生成",
      "Bug修复",
      "重构建议",
    ],
    featuresEn: [
      "Code Generation",
      "Performance Optimization",
      "Automated Testing",
      "Architecture Suggestions",
      "Code Review",
      "Documentation Generation",
      "Bug Fixing",
      "Refactoring Suggestions",
    ],
    icon: "💻",
    isFavorite: true,
    rating: 4.7,
    userRating: 5,
  },
  {
    id: "24",
    title: "健康管理",
    titleEn: "Health Management",
    description: "个性化健康管理与生活方式指导，提升生活质量",
    descriptionEn: "Personalized health management and lifestyle guidance to improve quality of life",
    features: [
      "健康评估",
      "饮食建议",
      "运动规划",
      "习惯优化",
      "睡眠分析",
      "压力管理",
      "健康追踪",
      "风险预警",
    ],
    featuresEn: [
      "Health Assessment",
      "Dietary Recommendations",
      "Exercise Planning",
      "Habit Optimization",
      "Sleep Analysis",
      "Stress Management",
      "Health Tracking",
      "Risk Warning",
    ],
    icon: "🏃",
    isFavorite: false,
    rating: 4.6,
    userRating: 0,
  },
];
